export const SET_LATEST_RECIPES = "SET_LATEST_RECIPES";
export const SELECT_LATEST_RECIPE = "SELECT_LATEST_RECIPE";
export const SET_LATEST_REFRESHING = "SET_LATEST_REFRESHING";
export const SET_LATEST_LOADING = "SET_LATEST_LOADING";

export const FETCH_RANDOM_RECIPE = "FETCH_RANDOM_RECIPE";

export const SET_FAVOURITE_RECIPE = "SET_FAVOURITE_REICPE";
export const SELECT_FAVOURIRE_RECIPE = "SELECT_FAVOURITE_RECIPE";
