export const SET_LATEST_RECIPES = "FETCH_LATEST_RECIPES";
export const SELECT_LATEST_RECIPE = "SELECT_LATEST_RECIPE";
export const SET_LATEST_REFRESHING = "SET_LATEST_REFRESHING";
export const SET_LATEST_LOADING = "SET_LATEST_LOADING";
